import {
  DEFAULT_SHELL,
  shellArgv,
  type ICheck,
  type ICheckContext,
  type ICheckIdentity,
  type IFinding,
  type IFixOutcome,
  type IProcessResult,
  type IShell,
} from '../../domain';
import { buildCheck, verdictFrom } from '../_shared';

export interface IRegenerableOptions extends ICheckIdentity {
  /** The generated artifact, repository-relative. */
  readonly artifact: string;
  /** A command that PRINTS the regenerated artifact to stdout (it must not write in
   * place — the check compares its output to the committed file without mutating). */
  readonly by: string;
  /** How to run `by`. Defaults to `bash -c`, which not every machine has. */
  readonly shell?: IShell;
  /** Kill the generator after this many seconds. A generator that hangs hangs the
   * whole run, and a run with no output is the worst diagnostic there is. */
  readonly timeoutSec?: number;
  /**
   * Offer `--fix`: write the regenerated bytes over the artifact.
   *
   * OPT-IN, not automatic, for one reason — declaring it adds the `write` capability
   * to this check's manifest permanently, and a repository that denies `write` to
   * every check would then lose the check itself rather than just the repair. A
   * consumer that wants the repair says so and accepts the capability.
   *
   * The repair is exact and cannot drift from the verdict: the check already holds
   * the generator's output, and the fix writes THAT, not a second invocation.
   */
  readonly fixable?: boolean;
}

/**
 * A generated artifact still matches what its generator produces — `router-mirror`,
 * `module-map`, `fe-map`. The failure mode this ends is a generated file hand-edited
 * out of sync, which reads as correct until the next regeneration silently reverts it.
 *
 * It declares `exec` (it runs the generator) and `read` (it reads the artifact), plus
 * `write` when the consumer asks for the repair; the engine denies any of them if
 * undeclared.
 *
 * It is the FIRST fixable check in this product, and that is worth saying out loud:
 * `--fix`, `IFixable`, the write gate and the re-run afterwards were all built and then
 * used by nothing for as long as they existed. A repair belongs here before anywhere
 * else because it is the one case with no judgement in it — the generator's output is
 * the correct content by definition, so the fix cannot be wrong in a way the check was
 * not already wrong about.
 */
export function regenerable(options: IRegenerableOptions): ICheck {
  const shell = options.shell ?? DEFAULT_SHELL;
  const generate = (ctx: ICheckContext): IProcessResult =>
    ctx.proc.run(shell.command, shellArgv(shell, options.by), { timeoutSec: options.timeoutSec });

  const check = buildCheck(options, options.fixable ? ['read', 'exec', 'write'] : ['read', 'exec'], (ctx) => {
    const findings: IFinding[] = [];
    const committed = ctx.files.tryRead(options.artifact);
    if (committed === undefined) {
      findings.push({ severity: 'error', file: options.artifact, message: `${options.artifact} does not exist to compare against.`, ruleId: options.id });
      return verdictFrom(findings);
    }
    const result = generate(ctx);
    if (result.status !== 0) {
      findings.push({ severity: 'error', file: options.artifact, message: `the generator \`${options.by}\` failed (exit ${result.status ?? 'signal'}).`, ruleId: options.id });
      return verdictFrom(findings);
    }
    if (result.stdout !== committed) {
      findings.push({
        severity: 'error',
        file: options.artifact,
        message:
          `${options.artifact} does not match what \`${options.by}\` produces — it is generated; regenerate it rather than editing by hand.` +
          (options.fixable ? ' `specwarden check --fix` writes it for you.' : ''),
        ruleId: options.id,
      });
    }
    return verdictFrom(findings);
  });

  if (!options.fixable) return check;

  /**
   * The repair. It re-runs the generator rather than carrying the verdict's output
   * forward, because `--fix` runs after the check and the tree may have moved between
   * them; regenerating is cheap and the alternative is writing bytes derived from a
   * state that no longer exists. A generator that fails here repairs nothing and says
   * so — the engine turns a throw into a finding, and the re-run reports what remains.
   */
  const fix = (ctx: ICheckContext): IFixOutcome => {
    const result = generate(ctx);
    if (result.status !== 0) {
      throw new Error(`the generator \`${options.by}\` failed (exit ${result.status ?? 'signal'}); ${options.artifact} was not written.`);
    }
    if (result.stdout === ctx.files.tryRead(options.artifact)) return { fixed: 0, summary: `${options.artifact} was already current` };
    ctx.writer.write(options.artifact, result.stdout);
    return { fixed: 1, summary: `regenerated ${options.artifact}` };
  };

  return Object.assign(check, { fix });
}
