/**
 * `CLAUDE.md` is `AGENTS.md` under another name.
 *
 * WHY TWO FILES AT ALL. Different agents look for different filenames, and neither will
 * read the other's. The choice is between one router under two names and two routers
 * that drift — and two routers drift in the worst possible way: each is individually
 * plausible, so nobody notices until an agent follows the stale one to a rule that moved.
 *
 * WHY GENERATED AND NOT SYMLINKED. A symlink does not survive every checkout, every
 * archive, or every editor; a generated file does, and a check proves it is current.
 *
 * The mirror carries a header saying it is generated. That header is the only difference
 * between the two files, and it is what stops somebody editing the copy.
 */
export const CANON = 'AGENTS.md';
export const MIRROR = 'CLAUDE.md';

const HEADER = [
  '<!--',
  `  GENERATED from ${CANON}. Do not edit this file.`,
  '',
  `  Different agents look for different filenames. One router under two names is the`,
  `  only arrangement that does not drift: edit ${CANON}, then run`,
  '  `pnpm check:router:write`.',
  '-->',
  '',
];

/** What the mirror must contain, given the canon. */
export const assembleMirror = (canon) => `${HEADER.join('\n')}${canon}`;

/** The problem with a mirror, or `undefined` when it is current. */
export function mirrorProblem(canon, mirror) {
  if (canon === undefined) return `${CANON} is missing — it is the router, and the mirror is derived from it.`;
  if (mirror === undefined) return `${MIRROR} is missing — run \`pnpm check:router:write\`.`;
  if (mirror !== assembleMirror(canon)) {
    return `${MIRROR} is not what ${CANON} assembles to. It is GENERATED: put the change in ${CANON}, then run \`pnpm check:router:write\`.`;
  }
  return undefined;
}
