/**
 * Pins `scaffold.mjs`: what `generated()` promises about every package, whatever the
 * registry holds.
 *
 * The drift gate compares the committed tree against this map, so a defect HERE is one
 * the drift gate cannot see — the committed files are regenerated from the same wrong
 * source and agree with it perfectly. These are the invariants a template-literal slip or
 * a registry edit would break with every other gate green.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, posix, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import { PACKAGES, pkgDeps, pkgDir, pkgName } from './registry.mjs';
import {
  PACKAGE_TABLE_END,
  PACKAGE_TABLE_START,
  generated,
  packageTable,
  vitestConfig,
  withPackageTable,
} from './scaffold.mjs';

const SCRIPT = resolve('scripts/scaffold.mjs');
const FILES = generated();

const manifestOf = (pkg) => JSON.parse(FILES.get(`${pkgDir(pkg)}/package.json`));
const siblings = new Set(PACKAGES.map(pkgName));
const ENGINE = PACKAGES.find((p) => p.kind === 'core');

describe('what the scaffolder generates', () => {
  it.each(PACKAGES.map((p) => [pkgName(p), p]))('gives %s every file a package owns', (_name, pkg) => {
    for (const file of [
      'package.json',
      'tsconfig.json',
      'vitest.config.ts',
      'tsup.config.ts',
      'README.md',
      'LICENSE',
    ]) {
      expect(FILES.has(`${pkgDir(pkg)}/${file}`), `${pkgDir(pkg)}/${file}`).toBe(true);
    }
  });

  it('includes the index a model is handed, so the drift gate compares it too', () => {
    // It was generated by a function nothing called, and had drifted the day it was first
    // compared. In the map, it cannot drift unseen again.
    expect(FILES.has('llms.txt')).toBe(true);
  });

  it('generates nothing empty — an empty file is a template that rendered to nothing', () => {
    const empty = [...FILES].filter(([, text]) => typeof text !== 'string' || text.trim() === '').map(([rel]) => rel);

    expect(empty).toEqual([]);
  });

  it('generates only JSON that parses', () => {
    const broken = [...FILES.keys()].filter((rel) => {
      if (!rel.endsWith('.json')) return false;
      try {
        JSON.parse(FILES.get(rel));
        return false;
      } catch {
        return true;
      }
    });

    expect(broken).toEqual([]);
  });

  it('keys every file by a relative forward-slashed path, which is what the drift gate reads back', () => {
    // A key built with `path.join` would be backslashed on Windows and name a file the
    // gate on Linux CI never finds.
    const odd = [...FILES.keys()].filter(
      (rel) => rel.includes('\\') || rel.startsWith('/') || rel !== posix.normalize(rel),
    );

    expect(odd).toEqual([]);
  });

  it("points every package's tsconfig at a base that exists — the engine sits one level down, not two", () => {
    for (const pkg of PACKAGES) {
      const { extends: base } = JSON.parse(FILES.get(`${pkgDir(pkg)}/tsconfig.json`));

      expect(existsSync(join(pkgDir(pkg), base)), `${pkgDir(pkg)} extends ${base}`).toBe(true);
    }
  });
});

describe("a template's README, and the parts it is assembled from", () => {
  const templates = PACKAGES.filter((p) => p.kind === 'template');
  const scaffold = PACKAGES.find((p) => p.kind === 'scaffold');

  it('installs with -D, names the template, and never the scaffold-parts it never installs on its own', () => {
    // It used to read `npm install @specwarden/template-x specwarden` — no `-D`, and
    // silent about the modules the generated tree actually imports. `@specwarden/scaffold-parts`
    // still shows up in the "It depends on" sentence below the command — that one names a
    // real dependency of the PACKAGE, not something to type on a command line.
    for (const pkg of templates) {
      const readme = FILES.get(`${pkgDir(pkg)}/README.md`);
      expect(readme, pkgName(pkg)).toContain(`pnpm add -D specwarden ${pkgName(pkg)}`);
      const command = readme.slice(readme.indexOf('```bash'), readme.indexOf('```', readme.indexOf('```bash') + 1));
      expect(command, pkgName(pkg)).not.toContain('@specwarden/scaffold-parts');
    }
  });

  it("names every module the generated tree imports, so a consumer's first run does not fail on one it never installed", () => {
    for (const pkg of templates) {
      const readme = FILES.get(`${pkgDir(pkg)}/README.md`);
      const install = readme.slice(readme.indexOf('pnpm add'), readme.indexOf('```', readme.indexOf('pnpm add')));
      for (const dep of pkgDeps(pkg).filter((d) => d !== '@specwarden/scaffold-parts')) {
        expect(install, `${pkgName(pkg)}: ${dep}`).toContain(dep);
      }
    }
  });

  it('says scaffold-parts is a build-time dependency, installed automatically, never a command of its own', () => {
    const readme = FILES.get(`${pkgDir(scaffold)}/README.md`);
    expect(readme).toContain('build-time dependency');
    const install = readme.slice(readme.indexOf('## Install'), readme.indexOf('## Documentation'));
    expect(install).not.toContain('```bash');
  });
});

describe('the dependency graph a manifest declares', () => {
  it('follows every sibling it depends on at runtime with workspace:^, never a pinned version', () => {
    // `workspace:^` becomes a caret range on publish, so a consumer's install tracks the
    // sibling; a literal version here ships a module wired to an engine it has outgrown.
    for (const pkg of PACKAGES) {
      for (const [name, spec] of Object.entries(manifestOf(pkg).dependencies ?? {})) {
        if (siblings.has(name)) expect(spec, `${pkgName(pkg)} → ${name}`).toBe('workspace:^');
      }
    }
  });

  it('resolves every sibling dev dependency from the workspace too', () => {
    for (const pkg of PACKAGES) {
      for (const [name, spec] of Object.entries(manifestOf(pkg).devDependencies ?? {})) {
        if (siblings.has(name)) expect(spec, `${pkgName(pkg)} → ${name}`).toMatch(/^workspace:/);
      }
    }
  });

  it('makes the engine a dependency of every package that is not the engine', () => {
    for (const pkg of PACKAGES.filter((p) => p.kind !== 'core')) {
      expect(manifestOf(pkg).dependencies?.specwarden, pkgName(pkg)).toBe('workspace:^');
    }
  });

  it('gives the engine no runtime dependency at all — it depends on nothing', () => {
    expect(manifestOf(ENGINE).dependencies ?? {}).toEqual({});
  });
});

describe('the coverage ratchet a vitest config carries', () => {
  it('refuses a package with no coverage entry rather than generating a config without a floor', () => {
    const bare = { ...PACKAGES[1], coverage: undefined };

    expect(() => vitestConfig(bare)).toThrow(/has no `coverage`/);
  });

  it.each(PACKAGES.map((p) => [pkgName(p), p]))(
    "embeds %s's registry thresholds and the date they were measured",
    (_name, pkg) => {
      const config = vitestConfig(pkg);
      const t = pkg.coverage;

      expect(config).toContain(
        `thresholds: { statements: ${t.statements}, branches: ${t.branches}, functions: ${t.functions}, lines: ${t.lines} }`,
      );
      expect(config).toContain(`Measured ${t.measured}.`);
      expect(FILES.get(`${pkgDir(pkg)}/vitest.config.ts`)).toBe(config);
    },
  );
});

describe('the package table in the root README', () => {
  const doc = (table) => `# specwarden\n\nhand-written prose\n\n${table}\n\nmore prose\n`;

  it('replaces exactly what sits between the markers, and nothing around them', () => {
    const before = doc(`${PACKAGE_TABLE_START}\n| stale |\n${PACKAGE_TABLE_END}`);

    expect(withPackageTable(before)).toBe(doc(packageTable()));
  });

  it('is a no-op on a document without the markers', () => {
    const plain = '# a README that never opted in\n\n| a | table |\n';

    expect(withPackageTable(plain)).toBe(plain);
  });

  it('is a no-op when only one marker is present, rather than cutting the document in half', () => {
    const half = `# x\n\n${PACKAGE_TABLE_START}\n| stale |\n`;

    expect(withPackageTable(half)).toBe(half);
  });

  it('is idempotent, so a scaffold run over a current README changes nothing', () => {
    const once = withPackageTable(doc(`${PACKAGE_TABLE_START}${PACKAGE_TABLE_END}`));

    expect(withPackageTable(once)).toBe(once);
  });

  it('lists every package in the registry', () => {
    const table = packageTable();

    for (const pkg of PACKAGES) expect(table).toContain(`\`${pkgName(pkg)}\``);
  });
});

describe('scaffold.mjs, run', () => {
  let scratch = null;

  afterEach(() => {
    if (scratch) rmSync(scratch, { recursive: true, force: true });
    scratch = null;
  });

  it('writes exactly the map it exports, and fills the README table in place', () => {
    // Run in a scratch tree, never here: the script writes. The tree holds what `main`
    // reads before it writes — the README it fills and the canon folder the index lists.
    scratch = mkdtempSync(join(tmpdir(), 'specwarden-scaffold-'));
    mkdirSync(join(scratch, 'skills'));
    writeFileSync(join(scratch, 'README.md'), `# x\n\n${PACKAGE_TABLE_START}\n${PACKAGE_TABLE_END}\n`, 'utf8');

    const output = execFileSync(process.execPath, [SCRIPT], { cwd: scratch, encoding: 'utf8', stdio: 'pipe' });

    expect(output).toMatch(new RegExp(`scaffolded \\d+ file\\(s\\) across ${PACKAGES.length} package\\(s\\)`));
    for (const pkg of PACKAGES) {
      expect(existsSync(join(scratch, pkgDir(pkg), 'package.json')), pkgDir(pkg)).toBe(true);
    }
    expect(readFileSync(join(scratch, 'README.md'), 'utf8')).toContain(packageTable());
  });
});
